Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Princesa");
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("Ao te ver, pela primeira vez");
Console.WriteLine("Eu tremi todo (tchu, tchu, tchu, tchu)");
Console.WriteLine("Uma coisa tomou conta");
Console.WriteLine("Do meu coração (tchu, tchu, tchu, tchu)");
Console.WriteLine("Com esse olhar meigo de menina (tchu, tchu, tchu, tchu)");
Console.WriteLine("Me fez nascer no peito esta paixão");
Console.WriteLine("E agora não durmo direito");
Console.WriteLine("Pensando em você (tchu, tchu, tchu, tchu)");
Console.WriteLine("Lembrando os seus olhos bonitos");
Console.WriteLine("Perdidos nos meus (tchu, tchu, tchu, tchu)");
Console.WriteLine("Que vontade louca que eu tenho");
Console.WriteLine("De tê-la comigo (tchu, tchu, tchu, tchu)");
Console.WriteLine("Calar sua boca bonita");
Console.WriteLine("Com um beijo meu");
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("Princesa, a deusa da minha poesia");
Console.WriteLine("Ternura da minha alegria");
Console.WriteLine("Nos meus sonhos quero te ver");
Console.WriteLine("Princesa, a musa dos meus pensamentos");
Console.WriteLine("Enfrento a chuva o mau tempo");
Console.WriteLine("Pra poder um pouco te ver");